name: Lint

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  go:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

      matrix:
        go_version:
          - '1.21'

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}

      - uses: actions/checkout@v4

      # This is outdated (latest is v7) but causes issues I don't wanna fix
      - uses: golangci/golangci-lint-action@v4
        with:
          version: latest
