name: Cross compile WireProxy

on:
  workflow_dispatch:
  release:
    types:
      - published
  push:
    tags:
      - '**'

jobs:
  lint:
    uses: "./.github/workflows/_lint.yml"

  build:
    needs: [ "lint" ]
    uses: "./.github/workflows/_build.yml"

  test:
    needs: [ "build" ]
    uses: "./.github/workflows/_test.yml"

  WireProxy:
    name: Publish WireProxy Binaries

    needs: [ "lint", "build", "test" ]

    runs-on: ubuntu-latest

    env:
      workdir: ./WireProxy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git clone WireProxy
        run: |
          git clone https://github.com/pufferffish/wireproxy.git ${{ env.workdir }}
          cp ./.github/wireproxy-releaser.yml ${{ env.workdir }}/.goreleaser.yml

      - name: Set up GoReleaser
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          workdir: ${{ env.workdir }}
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release binaries
        uses: softprops/action-gh-release@v2
        with:
          tag_name: wireproxy
          files: ${{ env.workdir }}/dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
